//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Week05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int AID { get; set; }
        public Nullable<int> JID { get; set; }
        public string ATitle { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Description { get; set; }
        public string Paper { get; set; }
    
        public virtual Journalist Journalist { get; set; }
    }
}
